# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-10-11 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(blank=True, max_length=200, null=True)),
                ('userid', models.IntegerField()),
                ('avatar_url', models.URLField()),
                ('gravatar_id', models.CharField(blank=True, max_length=200, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('html_url', models.URLField(blank=True, null=True)),
                ('followers_url', models.URLField(blank=True, null=True)),
                ('following_url', models.URLField(blank=True, null=True)),
                ('gists_url', models.URLField(blank=True, null=True)),
                ('starred_url', models.URLField(blank=True, null=True)),
                ('subscriptions_url', models.URLField(blank=True, null=True)),
                ('organizations_url', models.URLField(blank=True, null=True)),
                ('repos_url', models.URLField(blank=True, null=True)),
                ('events_url', models.URLField(blank=True, null=True)),
                ('received_events_url', models.URLField(blank=True, null=True)),
                ('acctype', models.CharField(blank=True, max_length=200, null=True)),
                ('site_admin', models.BooleanField()),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=30, null=True)),
                ('blog', models.CharField(blank=True, max_length=30, null=True)),
                ('location', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('hireable', models.BooleanField()),
                ('bio', models.CharField(blank=True, max_length=2000, null=True)),
                ('public_repos', models.IntegerField()),
                ('public_gists', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='gitusers',
            unique_together=set([('login',)]),
        ),
    ]
